<?php
  
 /**
 * Neoteric Global Variables
 *
 * This PHP file contains global constant definitions for database access and user prompt values.  This file has been converted to a .php file from a .inc file for security reasons.
 *
 * @package Includes
 * @company Neoteric Hovercraft, Inc
 * @author Collin Krepps
 */
  
 // Database access
 // Username to database server
 define('NEOUSER', "neo_user");
 // Password to database server
 define('NEOPASSWD', 'e.72hIwD$J');
 // IP address of database server
 define('NEODBIP', "mysql");
 // Database name
 define('NEODBNAME', "neoteric");
 // Database type
 define('NEODBTYPE', "mysql");
  
 // Installation prefix
 define('ABSPREFIX', "/usr/local/apache/sites/dev/neoteric/code");
 // Webserver's site prefix
 define('WEBPREFIX', "/code");
  
 // Values corresponding to user choice
 define('NO', "0");
 define('YES', "1");
 define('YESTOALL', "2");
 define('NOTOALL', "3");
 define('CANCEL', "4");
?>
